/// Token for both the layout DSL and scripting language
kind: Kind,
value: []const u8,
line: usize,
column: usize,

pub const Kind = enum {
    ident,
    number_lit,
    string_lit,
    semicolon,
    colon,
    comma,
    dot,
    dollar,
    equal,
    equal_equal,
    equal_greater_than,
    plus,
    plus_equal,
    minus,
    minus_equal,
    star,
    star_equal,
    slash,
    slash_equal,
    greater_than,
    greater_than_equal,
    less_than,
    less_than_equal,
    bang,
    bang_equal,
    left_bracket,
    right_bracket,
    left_square,
    right_square,
    left_brace,
    right_brace,
    func,
    @"enum",
    class,
    @"return",
    @"if",
    @"else",
    @"for",
    @"or",
    @"and",
    layout, // keyword for declaring layouts in script

    eof,
};
